# fly.toml app configuration file generated for evalutaionofcapstone-young-sun-5459 on 2024-12-12T12:26:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'evalutaionofcapstone-young-sun-5459'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
